name: build psyc
on: [push]
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Psyc
        uses: ./.github/actions/install-psyc
      - name: build
        run: psyc psyc.psy -b release && build/psyc_out -v && mv build/psyc_out build/psyc
      - uses: actions/upload-artifact@v4
        with:
          name: psyc-linux
          path: ./build/psyc
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Psyc
        uses: ./.github/actions/install-psyc
      - name: build
        shell: bash
        run: psyc psyc.psy -b release && ./build/psyc_out -v && mv build/psyc_out.exe build/psyc.exe
      - uses: actions/upload-artifact@v4
        with:
          name: psyc-windows
          path: ./build/psyc.exe
