name: Psyc Version Workflow
on: [push]
jobs:
  ver_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Psyc
        uses: ./.github/actions/fetch-latest-psyc
      - name: Print Version
        run: psyc.elf -v

