name: Psyc Version Workflow
on: [push]
jobs:
  ver_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Psyc
        uses: ./.github/actions/install-psyc
      - name: Print Version
        run: psyc.elf -v
  ver_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Psyc
        uses: ./.github/actions/install-psyc
      - name: Print Version
        shell: cmd
        run: psyc -v
